MEMCACHED_NAMESPACE=cytomineuliege
MEMCACHED_VERSION=v1.1.2

RABBITMQ_NAMESPACE=cytomineuliege
RABBITMQ_VERSION=v1.1.2

POSTGIS_NAMESPACE=cytomineuliege
POSTGIS_VERSION=v1.2.0

MONGODB_NAMESPACE=cytomineuliege
MONGODB_VERSION=v1.1.2

BACKUP_NAMESPACE=cytomineuliege
BACKUP_VERSION=v1.1.2

RETRIEVAL_NAMESPACE=cytomineuliege
RETRIEVAL_VERSION=v1.1.1

IIPJP2_NAMESPACE=cytomineuliege
IIPJP2_VERSION=v1.2.0

IIPCYTO_NAMESPACE=cytomineuliege
IIPCYTO_VERSION=v1.3.2

BIOFORMAT_NAMESPACE=cytomineuliege
BIOFORMAT_VERSION=v1.1.2

IMS_NAMESPACE=cytomineuliege
IMS_VERSION=v1.2.4

CORE_NAMESPACE=cytomineuliege
CORE_VERSION=v1.3.2

IRIS_NAMESPACE=cytomineuliege
IRIS_VERSION=v1.1.2

NGINX_NAMESPACE=cytomineuliege
NGINX_VERSION=v1.2.0

SLURM_NAMESPACE=cytomineuliege
SLURM_VERSION=v1.0.0

SOFTWAREROUTER_NAMESPACE=cytomineuliege
SOFTWAREROUTER_VERSION=v2.0.4